# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16966755ecc6ae9d96c762b7d3964a9e0df31816469057925e5cb875f41e7c3b7ca754c247c5f7df61772f53e5fdbeef603b8598f790d2eb381fd3a5d0c9876

test:
  secret_key_base: 5e9dd09cd9155d7588c4ef3e3e2cbd854566bc5b144f47cf0432169efdb96e1b7a838ca22d24dc28db0937f0058fdf8d5a11476b203f481c92cdd4c4319bf6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
